<?php
namespace App\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function create(UserEntity $user)
    {
        $this->em = $this->get('doctrine.orm.entity_manager');
        $this->em->persist($data);
        $this->em->flush();
    }
}
